### ISSUE TITLE
AoE Taunt mod missing custom announce

### ISSUE THREAD

**Issue by swetlover** [ennvina/silentrotate#15]
Hello,this addons add the AoE Taunt mod, but in the options, I cant find where to custom announce message.
All other modes have custom functions, AoE Taunt mod missing?
Thank you!

**Comment by ennvina** [comment]
Hello and sorry for the late reply.
You are right, the AoE taunt message is currently not configurable.
I have fixed it and it should be available for the next release.

**Comment by ennvina** [comment]
Fixed months ago and heavily tested since then. Closing the issue.
