### ISSUE TITLE
[enhancement] Multi-toc for automatic client compatibility

### ISSUE THREAD

**Issue by Road-block** [ennvina/silentrotate#31]
Also better handling by custom addon managers like wowup or ajour.

Essentially make use of the multitoc all wow client flavors support now [Basic Rules](https://wowpedia.fandom.com/wiki/TOC_format#Basic_rules)

If the SlientRotate package contains these 2 files.

- SilentRotate-Classic.toc
- SilentRotate-BCC.toc

they can have the appropriate `## Interface: xxxxxx` and the Classic-Era or BCC wow client will automatically load the correct one.
You can also have the traditional `SilentRotate.toc` file included which works as a fallback option if the wow client can't find a flavor specific .toc to load.

**Comment by ennvina** [comment]
Fixed in the following commit: https://github.com/ennvina/silentrotate/commit/a9086b4436a9b37854e77f712fd23e6acad82971

Will be available in the next release, which will be version 0.8.0.

Thank you for your support!

**Comment by ennvina** [comment]
@Road-block It works like a charm in the game client, but when publishing to CurseForge, they have tools that check the archive and they require the basic `SilentRotate.toc` file…

**Comment by Road-block** [comment]
Yeah, curseforge packager is slow on the uptake of new standards.  
What I'd do is use the highest supported version as the fallback .toc in addition to the client specific files.  

WoW client will load the client specific file anyway.
